/-
  Collatz — A machine-verified density exponent at level k = 14:
  γ = 50·log₂(101210/100000) = 0.8676, beating the 2003 record 0.84.
  Generated by analysis/kl_lean_instance.py. 1594323 classes in 729 shards.
  This file contains NO axioms and NO claim to prove the conjecture.
-/
import Collatz.KL14Check0
import Collatz.KL14Check1
import Collatz.KL14Check2
import Collatz.KL14Check3
import Collatz.KL14Check4
import Collatz.KL14Check5
import Collatz.KL14Check6
import Collatz.KL14Check7
import Collatz.KL14Check8

set_option exponentiation.threshold 2000
set_option maxRecDepth 100000

namespace Collatz
namespace K14
open G50

theorem check_all (i : ℕ) (hi : i < 1594323) : check i = true := by
  rcases Nat.lt_or_ge i 2187 with h0 | h0
  · exact okRange_sound check 12 0 2187 ok_0 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 4374 with h1 | h1
  · exact okRange_sound check 12 2187 4374 ok_1 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 6561 with h2 | h2
  · exact okRange_sound check 12 4374 6561 ok_2 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 8748 with h3 | h3
  · exact okRange_sound check 12 6561 8748 ok_3 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 10935 with h4 | h4
  · exact okRange_sound check 12 8748 10935 ok_4 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 13122 with h5 | h5
  · exact okRange_sound check 12 10935 13122 ok_5 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 15309 with h6 | h6
  · exact okRange_sound check 12 13122 15309 ok_6 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 17496 with h7 | h7
  · exact okRange_sound check 12 15309 17496 ok_7 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 19683 with h8 | h8
  · exact okRange_sound check 12 17496 19683 ok_8 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 21870 with h9 | h9
  · exact okRange_sound check 12 19683 21870 ok_9 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 24057 with h10 | h10
  · exact okRange_sound check 12 21870 24057 ok_10 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 26244 with h11 | h11
  · exact okRange_sound check 12 24057 26244 ok_11 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 28431 with h12 | h12
  · exact okRange_sound check 12 26244 28431 ok_12 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 30618 with h13 | h13
  · exact okRange_sound check 12 28431 30618 ok_13 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 32805 with h14 | h14
  · exact okRange_sound check 12 30618 32805 ok_14 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 34992 with h15 | h15
  · exact okRange_sound check 12 32805 34992 ok_15 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 37179 with h16 | h16
  · exact okRange_sound check 12 34992 37179 ok_16 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 39366 with h17 | h17
  · exact okRange_sound check 12 37179 39366 ok_17 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 41553 with h18 | h18
  · exact okRange_sound check 12 39366 41553 ok_18 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 43740 with h19 | h19
  · exact okRange_sound check 12 41553 43740 ok_19 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 45927 with h20 | h20
  · exact okRange_sound check 12 43740 45927 ok_20 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 48114 with h21 | h21
  · exact okRange_sound check 12 45927 48114 ok_21 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 50301 with h22 | h22
  · exact okRange_sound check 12 48114 50301 ok_22 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 52488 with h23 | h23
  · exact okRange_sound check 12 50301 52488 ok_23 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 54675 with h24 | h24
  · exact okRange_sound check 12 52488 54675 ok_24 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 56862 with h25 | h25
  · exact okRange_sound check 12 54675 56862 ok_25 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 59049 with h26 | h26
  · exact okRange_sound check 12 56862 59049 ok_26 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 61236 with h27 | h27
  · exact okRange_sound check 12 59049 61236 ok_27 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 63423 with h28 | h28
  · exact okRange_sound check 12 61236 63423 ok_28 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 65610 with h29 | h29
  · exact okRange_sound check 12 63423 65610 ok_29 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 67797 with h30 | h30
  · exact okRange_sound check 12 65610 67797 ok_30 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 69984 with h31 | h31
  · exact okRange_sound check 12 67797 69984 ok_31 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 72171 with h32 | h32
  · exact okRange_sound check 12 69984 72171 ok_32 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 74358 with h33 | h33
  · exact okRange_sound check 12 72171 74358 ok_33 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 76545 with h34 | h34
  · exact okRange_sound check 12 74358 76545 ok_34 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 78732 with h35 | h35
  · exact okRange_sound check 12 76545 78732 ok_35 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 80919 with h36 | h36
  · exact okRange_sound check 12 78732 80919 ok_36 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 83106 with h37 | h37
  · exact okRange_sound check 12 80919 83106 ok_37 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 85293 with h38 | h38
  · exact okRange_sound check 12 83106 85293 ok_38 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 87480 with h39 | h39
  · exact okRange_sound check 12 85293 87480 ok_39 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 89667 with h40 | h40
  · exact okRange_sound check 12 87480 89667 ok_40 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 91854 with h41 | h41
  · exact okRange_sound check 12 89667 91854 ok_41 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 94041 with h42 | h42
  · exact okRange_sound check 12 91854 94041 ok_42 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 96228 with h43 | h43
  · exact okRange_sound check 12 94041 96228 ok_43 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 98415 with h44 | h44
  · exact okRange_sound check 12 96228 98415 ok_44 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 100602 with h45 | h45
  · exact okRange_sound check 12 98415 100602 ok_45 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 102789 with h46 | h46
  · exact okRange_sound check 12 100602 102789 ok_46 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 104976 with h47 | h47
  · exact okRange_sound check 12 102789 104976 ok_47 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 107163 with h48 | h48
  · exact okRange_sound check 12 104976 107163 ok_48 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 109350 with h49 | h49
  · exact okRange_sound check 12 107163 109350 ok_49 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 111537 with h50 | h50
  · exact okRange_sound check 12 109350 111537 ok_50 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 113724 with h51 | h51
  · exact okRange_sound check 12 111537 113724 ok_51 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 115911 with h52 | h52
  · exact okRange_sound check 12 113724 115911 ok_52 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 118098 with h53 | h53
  · exact okRange_sound check 12 115911 118098 ok_53 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 120285 with h54 | h54
  · exact okRange_sound check 12 118098 120285 ok_54 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 122472 with h55 | h55
  · exact okRange_sound check 12 120285 122472 ok_55 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 124659 with h56 | h56
  · exact okRange_sound check 12 122472 124659 ok_56 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 126846 with h57 | h57
  · exact okRange_sound check 12 124659 126846 ok_57 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 129033 with h58 | h58
  · exact okRange_sound check 12 126846 129033 ok_58 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 131220 with h59 | h59
  · exact okRange_sound check 12 129033 131220 ok_59 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 133407 with h60 | h60
  · exact okRange_sound check 12 131220 133407 ok_60 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 135594 with h61 | h61
  · exact okRange_sound check 12 133407 135594 ok_61 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 137781 with h62 | h62
  · exact okRange_sound check 12 135594 137781 ok_62 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 139968 with h63 | h63
  · exact okRange_sound check 12 137781 139968 ok_63 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 142155 with h64 | h64
  · exact okRange_sound check 12 139968 142155 ok_64 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 144342 with h65 | h65
  · exact okRange_sound check 12 142155 144342 ok_65 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 146529 with h66 | h66
  · exact okRange_sound check 12 144342 146529 ok_66 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 148716 with h67 | h67
  · exact okRange_sound check 12 146529 148716 ok_67 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 150903 with h68 | h68
  · exact okRange_sound check 12 148716 150903 ok_68 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 153090 with h69 | h69
  · exact okRange_sound check 12 150903 153090 ok_69 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 155277 with h70 | h70
  · exact okRange_sound check 12 153090 155277 ok_70 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 157464 with h71 | h71
  · exact okRange_sound check 12 155277 157464 ok_71 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 159651 with h72 | h72
  · exact okRange_sound check 12 157464 159651 ok_72 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 161838 with h73 | h73
  · exact okRange_sound check 12 159651 161838 ok_73 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 164025 with h74 | h74
  · exact okRange_sound check 12 161838 164025 ok_74 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 166212 with h75 | h75
  · exact okRange_sound check 12 164025 166212 ok_75 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 168399 with h76 | h76
  · exact okRange_sound check 12 166212 168399 ok_76 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 170586 with h77 | h77
  · exact okRange_sound check 12 168399 170586 ok_77 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 172773 with h78 | h78
  · exact okRange_sound check 12 170586 172773 ok_78 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 174960 with h79 | h79
  · exact okRange_sound check 12 172773 174960 ok_79 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 177147 with h80 | h80
  · exact okRange_sound check 12 174960 177147 ok_80 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 179334 with h81 | h81
  · exact okRange_sound check 12 177147 179334 ok_81 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 181521 with h82 | h82
  · exact okRange_sound check 12 179334 181521 ok_82 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 183708 with h83 | h83
  · exact okRange_sound check 12 181521 183708 ok_83 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 185895 with h84 | h84
  · exact okRange_sound check 12 183708 185895 ok_84 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 188082 with h85 | h85
  · exact okRange_sound check 12 185895 188082 ok_85 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 190269 with h86 | h86
  · exact okRange_sound check 12 188082 190269 ok_86 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 192456 with h87 | h87
  · exact okRange_sound check 12 190269 192456 ok_87 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 194643 with h88 | h88
  · exact okRange_sound check 12 192456 194643 ok_88 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 196830 with h89 | h89
  · exact okRange_sound check 12 194643 196830 ok_89 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 199017 with h90 | h90
  · exact okRange_sound check 12 196830 199017 ok_90 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 201204 with h91 | h91
  · exact okRange_sound check 12 199017 201204 ok_91 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 203391 with h92 | h92
  · exact okRange_sound check 12 201204 203391 ok_92 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 205578 with h93 | h93
  · exact okRange_sound check 12 203391 205578 ok_93 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 207765 with h94 | h94
  · exact okRange_sound check 12 205578 207765 ok_94 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 209952 with h95 | h95
  · exact okRange_sound check 12 207765 209952 ok_95 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 212139 with h96 | h96
  · exact okRange_sound check 12 209952 212139 ok_96 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 214326 with h97 | h97
  · exact okRange_sound check 12 212139 214326 ok_97 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 216513 with h98 | h98
  · exact okRange_sound check 12 214326 216513 ok_98 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 218700 with h99 | h99
  · exact okRange_sound check 12 216513 218700 ok_99 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 220887 with h100 | h100
  · exact okRange_sound check 12 218700 220887 ok_100 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 223074 with h101 | h101
  · exact okRange_sound check 12 220887 223074 ok_101 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 225261 with h102 | h102
  · exact okRange_sound check 12 223074 225261 ok_102 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 227448 with h103 | h103
  · exact okRange_sound check 12 225261 227448 ok_103 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 229635 with h104 | h104
  · exact okRange_sound check 12 227448 229635 ok_104 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 231822 with h105 | h105
  · exact okRange_sound check 12 229635 231822 ok_105 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 234009 with h106 | h106
  · exact okRange_sound check 12 231822 234009 ok_106 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 236196 with h107 | h107
  · exact okRange_sound check 12 234009 236196 ok_107 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 238383 with h108 | h108
  · exact okRange_sound check 12 236196 238383 ok_108 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 240570 with h109 | h109
  · exact okRange_sound check 12 238383 240570 ok_109 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 242757 with h110 | h110
  · exact okRange_sound check 12 240570 242757 ok_110 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 244944 with h111 | h111
  · exact okRange_sound check 12 242757 244944 ok_111 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 247131 with h112 | h112
  · exact okRange_sound check 12 244944 247131 ok_112 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 249318 with h113 | h113
  · exact okRange_sound check 12 247131 249318 ok_113 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 251505 with h114 | h114
  · exact okRange_sound check 12 249318 251505 ok_114 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 253692 with h115 | h115
  · exact okRange_sound check 12 251505 253692 ok_115 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 255879 with h116 | h116
  · exact okRange_sound check 12 253692 255879 ok_116 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 258066 with h117 | h117
  · exact okRange_sound check 12 255879 258066 ok_117 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 260253 with h118 | h118
  · exact okRange_sound check 12 258066 260253 ok_118 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 262440 with h119 | h119
  · exact okRange_sound check 12 260253 262440 ok_119 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 264627 with h120 | h120
  · exact okRange_sound check 12 262440 264627 ok_120 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 266814 with h121 | h121
  · exact okRange_sound check 12 264627 266814 ok_121 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 269001 with h122 | h122
  · exact okRange_sound check 12 266814 269001 ok_122 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 271188 with h123 | h123
  · exact okRange_sound check 12 269001 271188 ok_123 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 273375 with h124 | h124
  · exact okRange_sound check 12 271188 273375 ok_124 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 275562 with h125 | h125
  · exact okRange_sound check 12 273375 275562 ok_125 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 277749 with h126 | h126
  · exact okRange_sound check 12 275562 277749 ok_126 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 279936 with h127 | h127
  · exact okRange_sound check 12 277749 279936 ok_127 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 282123 with h128 | h128
  · exact okRange_sound check 12 279936 282123 ok_128 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 284310 with h129 | h129
  · exact okRange_sound check 12 282123 284310 ok_129 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 286497 with h130 | h130
  · exact okRange_sound check 12 284310 286497 ok_130 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 288684 with h131 | h131
  · exact okRange_sound check 12 286497 288684 ok_131 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 290871 with h132 | h132
  · exact okRange_sound check 12 288684 290871 ok_132 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 293058 with h133 | h133
  · exact okRange_sound check 12 290871 293058 ok_133 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 295245 with h134 | h134
  · exact okRange_sound check 12 293058 295245 ok_134 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 297432 with h135 | h135
  · exact okRange_sound check 12 295245 297432 ok_135 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 299619 with h136 | h136
  · exact okRange_sound check 12 297432 299619 ok_136 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 301806 with h137 | h137
  · exact okRange_sound check 12 299619 301806 ok_137 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 303993 with h138 | h138
  · exact okRange_sound check 12 301806 303993 ok_138 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 306180 with h139 | h139
  · exact okRange_sound check 12 303993 306180 ok_139 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 308367 with h140 | h140
  · exact okRange_sound check 12 306180 308367 ok_140 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 310554 with h141 | h141
  · exact okRange_sound check 12 308367 310554 ok_141 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 312741 with h142 | h142
  · exact okRange_sound check 12 310554 312741 ok_142 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 314928 with h143 | h143
  · exact okRange_sound check 12 312741 314928 ok_143 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 317115 with h144 | h144
  · exact okRange_sound check 12 314928 317115 ok_144 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 319302 with h145 | h145
  · exact okRange_sound check 12 317115 319302 ok_145 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 321489 with h146 | h146
  · exact okRange_sound check 12 319302 321489 ok_146 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 323676 with h147 | h147
  · exact okRange_sound check 12 321489 323676 ok_147 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 325863 with h148 | h148
  · exact okRange_sound check 12 323676 325863 ok_148 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 328050 with h149 | h149
  · exact okRange_sound check 12 325863 328050 ok_149 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 330237 with h150 | h150
  · exact okRange_sound check 12 328050 330237 ok_150 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 332424 with h151 | h151
  · exact okRange_sound check 12 330237 332424 ok_151 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 334611 with h152 | h152
  · exact okRange_sound check 12 332424 334611 ok_152 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 336798 with h153 | h153
  · exact okRange_sound check 12 334611 336798 ok_153 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 338985 with h154 | h154
  · exact okRange_sound check 12 336798 338985 ok_154 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 341172 with h155 | h155
  · exact okRange_sound check 12 338985 341172 ok_155 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 343359 with h156 | h156
  · exact okRange_sound check 12 341172 343359 ok_156 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 345546 with h157 | h157
  · exact okRange_sound check 12 343359 345546 ok_157 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 347733 with h158 | h158
  · exact okRange_sound check 12 345546 347733 ok_158 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 349920 with h159 | h159
  · exact okRange_sound check 12 347733 349920 ok_159 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 352107 with h160 | h160
  · exact okRange_sound check 12 349920 352107 ok_160 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 354294 with h161 | h161
  · exact okRange_sound check 12 352107 354294 ok_161 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 356481 with h162 | h162
  · exact okRange_sound check 12 354294 356481 ok_162 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 358668 with h163 | h163
  · exact okRange_sound check 12 356481 358668 ok_163 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 360855 with h164 | h164
  · exact okRange_sound check 12 358668 360855 ok_164 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 363042 with h165 | h165
  · exact okRange_sound check 12 360855 363042 ok_165 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 365229 with h166 | h166
  · exact okRange_sound check 12 363042 365229 ok_166 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 367416 with h167 | h167
  · exact okRange_sound check 12 365229 367416 ok_167 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 369603 with h168 | h168
  · exact okRange_sound check 12 367416 369603 ok_168 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 371790 with h169 | h169
  · exact okRange_sound check 12 369603 371790 ok_169 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 373977 with h170 | h170
  · exact okRange_sound check 12 371790 373977 ok_170 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 376164 with h171 | h171
  · exact okRange_sound check 12 373977 376164 ok_171 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 378351 with h172 | h172
  · exact okRange_sound check 12 376164 378351 ok_172 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 380538 with h173 | h173
  · exact okRange_sound check 12 378351 380538 ok_173 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 382725 with h174 | h174
  · exact okRange_sound check 12 380538 382725 ok_174 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 384912 with h175 | h175
  · exact okRange_sound check 12 382725 384912 ok_175 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 387099 with h176 | h176
  · exact okRange_sound check 12 384912 387099 ok_176 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 389286 with h177 | h177
  · exact okRange_sound check 12 387099 389286 ok_177 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 391473 with h178 | h178
  · exact okRange_sound check 12 389286 391473 ok_178 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 393660 with h179 | h179
  · exact okRange_sound check 12 391473 393660 ok_179 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 395847 with h180 | h180
  · exact okRange_sound check 12 393660 395847 ok_180 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 398034 with h181 | h181
  · exact okRange_sound check 12 395847 398034 ok_181 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 400221 with h182 | h182
  · exact okRange_sound check 12 398034 400221 ok_182 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 402408 with h183 | h183
  · exact okRange_sound check 12 400221 402408 ok_183 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 404595 with h184 | h184
  · exact okRange_sound check 12 402408 404595 ok_184 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 406782 with h185 | h185
  · exact okRange_sound check 12 404595 406782 ok_185 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 408969 with h186 | h186
  · exact okRange_sound check 12 406782 408969 ok_186 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 411156 with h187 | h187
  · exact okRange_sound check 12 408969 411156 ok_187 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 413343 with h188 | h188
  · exact okRange_sound check 12 411156 413343 ok_188 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 415530 with h189 | h189
  · exact okRange_sound check 12 413343 415530 ok_189 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 417717 with h190 | h190
  · exact okRange_sound check 12 415530 417717 ok_190 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 419904 with h191 | h191
  · exact okRange_sound check 12 417717 419904 ok_191 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 422091 with h192 | h192
  · exact okRange_sound check 12 419904 422091 ok_192 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 424278 with h193 | h193
  · exact okRange_sound check 12 422091 424278 ok_193 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 426465 with h194 | h194
  · exact okRange_sound check 12 424278 426465 ok_194 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 428652 with h195 | h195
  · exact okRange_sound check 12 426465 428652 ok_195 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 430839 with h196 | h196
  · exact okRange_sound check 12 428652 430839 ok_196 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 433026 with h197 | h197
  · exact okRange_sound check 12 430839 433026 ok_197 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 435213 with h198 | h198
  · exact okRange_sound check 12 433026 435213 ok_198 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 437400 with h199 | h199
  · exact okRange_sound check 12 435213 437400 ok_199 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 439587 with h200 | h200
  · exact okRange_sound check 12 437400 439587 ok_200 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 441774 with h201 | h201
  · exact okRange_sound check 12 439587 441774 ok_201 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 443961 with h202 | h202
  · exact okRange_sound check 12 441774 443961 ok_202 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 446148 with h203 | h203
  · exact okRange_sound check 12 443961 446148 ok_203 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 448335 with h204 | h204
  · exact okRange_sound check 12 446148 448335 ok_204 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 450522 with h205 | h205
  · exact okRange_sound check 12 448335 450522 ok_205 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 452709 with h206 | h206
  · exact okRange_sound check 12 450522 452709 ok_206 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 454896 with h207 | h207
  · exact okRange_sound check 12 452709 454896 ok_207 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 457083 with h208 | h208
  · exact okRange_sound check 12 454896 457083 ok_208 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 459270 with h209 | h209
  · exact okRange_sound check 12 457083 459270 ok_209 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 461457 with h210 | h210
  · exact okRange_sound check 12 459270 461457 ok_210 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 463644 with h211 | h211
  · exact okRange_sound check 12 461457 463644 ok_211 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 465831 with h212 | h212
  · exact okRange_sound check 12 463644 465831 ok_212 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 468018 with h213 | h213
  · exact okRange_sound check 12 465831 468018 ok_213 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 470205 with h214 | h214
  · exact okRange_sound check 12 468018 470205 ok_214 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 472392 with h215 | h215
  · exact okRange_sound check 12 470205 472392 ok_215 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 474579 with h216 | h216
  · exact okRange_sound check 12 472392 474579 ok_216 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 476766 with h217 | h217
  · exact okRange_sound check 12 474579 476766 ok_217 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 478953 with h218 | h218
  · exact okRange_sound check 12 476766 478953 ok_218 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 481140 with h219 | h219
  · exact okRange_sound check 12 478953 481140 ok_219 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 483327 with h220 | h220
  · exact okRange_sound check 12 481140 483327 ok_220 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 485514 with h221 | h221
  · exact okRange_sound check 12 483327 485514 ok_221 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 487701 with h222 | h222
  · exact okRange_sound check 12 485514 487701 ok_222 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 489888 with h223 | h223
  · exact okRange_sound check 12 487701 489888 ok_223 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 492075 with h224 | h224
  · exact okRange_sound check 12 489888 492075 ok_224 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 494262 with h225 | h225
  · exact okRange_sound check 12 492075 494262 ok_225 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 496449 with h226 | h226
  · exact okRange_sound check 12 494262 496449 ok_226 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 498636 with h227 | h227
  · exact okRange_sound check 12 496449 498636 ok_227 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 500823 with h228 | h228
  · exact okRange_sound check 12 498636 500823 ok_228 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 503010 with h229 | h229
  · exact okRange_sound check 12 500823 503010 ok_229 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 505197 with h230 | h230
  · exact okRange_sound check 12 503010 505197 ok_230 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 507384 with h231 | h231
  · exact okRange_sound check 12 505197 507384 ok_231 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 509571 with h232 | h232
  · exact okRange_sound check 12 507384 509571 ok_232 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 511758 with h233 | h233
  · exact okRange_sound check 12 509571 511758 ok_233 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 513945 with h234 | h234
  · exact okRange_sound check 12 511758 513945 ok_234 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 516132 with h235 | h235
  · exact okRange_sound check 12 513945 516132 ok_235 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 518319 with h236 | h236
  · exact okRange_sound check 12 516132 518319 ok_236 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 520506 with h237 | h237
  · exact okRange_sound check 12 518319 520506 ok_237 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 522693 with h238 | h238
  · exact okRange_sound check 12 520506 522693 ok_238 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 524880 with h239 | h239
  · exact okRange_sound check 12 522693 524880 ok_239 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 527067 with h240 | h240
  · exact okRange_sound check 12 524880 527067 ok_240 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 529254 with h241 | h241
  · exact okRange_sound check 12 527067 529254 ok_241 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 531441 with h242 | h242
  · exact okRange_sound check 12 529254 531441 ok_242 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 533628 with h243 | h243
  · exact okRange_sound check 12 531441 533628 ok_243 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 535815 with h244 | h244
  · exact okRange_sound check 12 533628 535815 ok_244 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 538002 with h245 | h245
  · exact okRange_sound check 12 535815 538002 ok_245 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 540189 with h246 | h246
  · exact okRange_sound check 12 538002 540189 ok_246 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 542376 with h247 | h247
  · exact okRange_sound check 12 540189 542376 ok_247 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 544563 with h248 | h248
  · exact okRange_sound check 12 542376 544563 ok_248 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 546750 with h249 | h249
  · exact okRange_sound check 12 544563 546750 ok_249 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 548937 with h250 | h250
  · exact okRange_sound check 12 546750 548937 ok_250 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 551124 with h251 | h251
  · exact okRange_sound check 12 548937 551124 ok_251 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 553311 with h252 | h252
  · exact okRange_sound check 12 551124 553311 ok_252 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 555498 with h253 | h253
  · exact okRange_sound check 12 553311 555498 ok_253 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 557685 with h254 | h254
  · exact okRange_sound check 12 555498 557685 ok_254 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 559872 with h255 | h255
  · exact okRange_sound check 12 557685 559872 ok_255 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 562059 with h256 | h256
  · exact okRange_sound check 12 559872 562059 ok_256 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 564246 with h257 | h257
  · exact okRange_sound check 12 562059 564246 ok_257 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 566433 with h258 | h258
  · exact okRange_sound check 12 564246 566433 ok_258 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 568620 with h259 | h259
  · exact okRange_sound check 12 566433 568620 ok_259 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 570807 with h260 | h260
  · exact okRange_sound check 12 568620 570807 ok_260 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 572994 with h261 | h261
  · exact okRange_sound check 12 570807 572994 ok_261 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 575181 with h262 | h262
  · exact okRange_sound check 12 572994 575181 ok_262 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 577368 with h263 | h263
  · exact okRange_sound check 12 575181 577368 ok_263 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 579555 with h264 | h264
  · exact okRange_sound check 12 577368 579555 ok_264 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 581742 with h265 | h265
  · exact okRange_sound check 12 579555 581742 ok_265 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 583929 with h266 | h266
  · exact okRange_sound check 12 581742 583929 ok_266 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 586116 with h267 | h267
  · exact okRange_sound check 12 583929 586116 ok_267 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 588303 with h268 | h268
  · exact okRange_sound check 12 586116 588303 ok_268 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 590490 with h269 | h269
  · exact okRange_sound check 12 588303 590490 ok_269 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 592677 with h270 | h270
  · exact okRange_sound check 12 590490 592677 ok_270 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 594864 with h271 | h271
  · exact okRange_sound check 12 592677 594864 ok_271 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 597051 with h272 | h272
  · exact okRange_sound check 12 594864 597051 ok_272 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 599238 with h273 | h273
  · exact okRange_sound check 12 597051 599238 ok_273 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 601425 with h274 | h274
  · exact okRange_sound check 12 599238 601425 ok_274 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 603612 with h275 | h275
  · exact okRange_sound check 12 601425 603612 ok_275 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 605799 with h276 | h276
  · exact okRange_sound check 12 603612 605799 ok_276 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 607986 with h277 | h277
  · exact okRange_sound check 12 605799 607986 ok_277 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 610173 with h278 | h278
  · exact okRange_sound check 12 607986 610173 ok_278 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 612360 with h279 | h279
  · exact okRange_sound check 12 610173 612360 ok_279 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 614547 with h280 | h280
  · exact okRange_sound check 12 612360 614547 ok_280 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 616734 with h281 | h281
  · exact okRange_sound check 12 614547 616734 ok_281 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 618921 with h282 | h282
  · exact okRange_sound check 12 616734 618921 ok_282 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 621108 with h283 | h283
  · exact okRange_sound check 12 618921 621108 ok_283 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 623295 with h284 | h284
  · exact okRange_sound check 12 621108 623295 ok_284 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 625482 with h285 | h285
  · exact okRange_sound check 12 623295 625482 ok_285 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 627669 with h286 | h286
  · exact okRange_sound check 12 625482 627669 ok_286 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 629856 with h287 | h287
  · exact okRange_sound check 12 627669 629856 ok_287 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 632043 with h288 | h288
  · exact okRange_sound check 12 629856 632043 ok_288 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 634230 with h289 | h289
  · exact okRange_sound check 12 632043 634230 ok_289 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 636417 with h290 | h290
  · exact okRange_sound check 12 634230 636417 ok_290 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 638604 with h291 | h291
  · exact okRange_sound check 12 636417 638604 ok_291 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 640791 with h292 | h292
  · exact okRange_sound check 12 638604 640791 ok_292 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 642978 with h293 | h293
  · exact okRange_sound check 12 640791 642978 ok_293 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 645165 with h294 | h294
  · exact okRange_sound check 12 642978 645165 ok_294 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 647352 with h295 | h295
  · exact okRange_sound check 12 645165 647352 ok_295 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 649539 with h296 | h296
  · exact okRange_sound check 12 647352 649539 ok_296 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 651726 with h297 | h297
  · exact okRange_sound check 12 649539 651726 ok_297 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 653913 with h298 | h298
  · exact okRange_sound check 12 651726 653913 ok_298 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 656100 with h299 | h299
  · exact okRange_sound check 12 653913 656100 ok_299 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 658287 with h300 | h300
  · exact okRange_sound check 12 656100 658287 ok_300 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 660474 with h301 | h301
  · exact okRange_sound check 12 658287 660474 ok_301 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 662661 with h302 | h302
  · exact okRange_sound check 12 660474 662661 ok_302 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 664848 with h303 | h303
  · exact okRange_sound check 12 662661 664848 ok_303 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 667035 with h304 | h304
  · exact okRange_sound check 12 664848 667035 ok_304 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 669222 with h305 | h305
  · exact okRange_sound check 12 667035 669222 ok_305 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 671409 with h306 | h306
  · exact okRange_sound check 12 669222 671409 ok_306 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 673596 with h307 | h307
  · exact okRange_sound check 12 671409 673596 ok_307 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 675783 with h308 | h308
  · exact okRange_sound check 12 673596 675783 ok_308 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 677970 with h309 | h309
  · exact okRange_sound check 12 675783 677970 ok_309 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 680157 with h310 | h310
  · exact okRange_sound check 12 677970 680157 ok_310 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 682344 with h311 | h311
  · exact okRange_sound check 12 680157 682344 ok_311 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 684531 with h312 | h312
  · exact okRange_sound check 12 682344 684531 ok_312 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 686718 with h313 | h313
  · exact okRange_sound check 12 684531 686718 ok_313 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 688905 with h314 | h314
  · exact okRange_sound check 12 686718 688905 ok_314 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 691092 with h315 | h315
  · exact okRange_sound check 12 688905 691092 ok_315 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 693279 with h316 | h316
  · exact okRange_sound check 12 691092 693279 ok_316 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 695466 with h317 | h317
  · exact okRange_sound check 12 693279 695466 ok_317 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 697653 with h318 | h318
  · exact okRange_sound check 12 695466 697653 ok_318 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 699840 with h319 | h319
  · exact okRange_sound check 12 697653 699840 ok_319 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 702027 with h320 | h320
  · exact okRange_sound check 12 699840 702027 ok_320 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 704214 with h321 | h321
  · exact okRange_sound check 12 702027 704214 ok_321 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 706401 with h322 | h322
  · exact okRange_sound check 12 704214 706401 ok_322 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 708588 with h323 | h323
  · exact okRange_sound check 12 706401 708588 ok_323 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 710775 with h324 | h324
  · exact okRange_sound check 12 708588 710775 ok_324 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 712962 with h325 | h325
  · exact okRange_sound check 12 710775 712962 ok_325 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 715149 with h326 | h326
  · exact okRange_sound check 12 712962 715149 ok_326 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 717336 with h327 | h327
  · exact okRange_sound check 12 715149 717336 ok_327 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 719523 with h328 | h328
  · exact okRange_sound check 12 717336 719523 ok_328 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 721710 with h329 | h329
  · exact okRange_sound check 12 719523 721710 ok_329 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 723897 with h330 | h330
  · exact okRange_sound check 12 721710 723897 ok_330 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 726084 with h331 | h331
  · exact okRange_sound check 12 723897 726084 ok_331 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 728271 with h332 | h332
  · exact okRange_sound check 12 726084 728271 ok_332 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 730458 with h333 | h333
  · exact okRange_sound check 12 728271 730458 ok_333 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 732645 with h334 | h334
  · exact okRange_sound check 12 730458 732645 ok_334 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 734832 with h335 | h335
  · exact okRange_sound check 12 732645 734832 ok_335 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 737019 with h336 | h336
  · exact okRange_sound check 12 734832 737019 ok_336 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 739206 with h337 | h337
  · exact okRange_sound check 12 737019 739206 ok_337 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 741393 with h338 | h338
  · exact okRange_sound check 12 739206 741393 ok_338 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 743580 with h339 | h339
  · exact okRange_sound check 12 741393 743580 ok_339 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 745767 with h340 | h340
  · exact okRange_sound check 12 743580 745767 ok_340 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 747954 with h341 | h341
  · exact okRange_sound check 12 745767 747954 ok_341 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 750141 with h342 | h342
  · exact okRange_sound check 12 747954 750141 ok_342 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 752328 with h343 | h343
  · exact okRange_sound check 12 750141 752328 ok_343 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 754515 with h344 | h344
  · exact okRange_sound check 12 752328 754515 ok_344 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 756702 with h345 | h345
  · exact okRange_sound check 12 754515 756702 ok_345 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 758889 with h346 | h346
  · exact okRange_sound check 12 756702 758889 ok_346 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 761076 with h347 | h347
  · exact okRange_sound check 12 758889 761076 ok_347 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 763263 with h348 | h348
  · exact okRange_sound check 12 761076 763263 ok_348 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 765450 with h349 | h349
  · exact okRange_sound check 12 763263 765450 ok_349 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 767637 with h350 | h350
  · exact okRange_sound check 12 765450 767637 ok_350 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 769824 with h351 | h351
  · exact okRange_sound check 12 767637 769824 ok_351 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 772011 with h352 | h352
  · exact okRange_sound check 12 769824 772011 ok_352 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 774198 with h353 | h353
  · exact okRange_sound check 12 772011 774198 ok_353 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 776385 with h354 | h354
  · exact okRange_sound check 12 774198 776385 ok_354 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 778572 with h355 | h355
  · exact okRange_sound check 12 776385 778572 ok_355 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 780759 with h356 | h356
  · exact okRange_sound check 12 778572 780759 ok_356 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 782946 with h357 | h357
  · exact okRange_sound check 12 780759 782946 ok_357 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 785133 with h358 | h358
  · exact okRange_sound check 12 782946 785133 ok_358 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 787320 with h359 | h359
  · exact okRange_sound check 12 785133 787320 ok_359 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 789507 with h360 | h360
  · exact okRange_sound check 12 787320 789507 ok_360 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 791694 with h361 | h361
  · exact okRange_sound check 12 789507 791694 ok_361 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 793881 with h362 | h362
  · exact okRange_sound check 12 791694 793881 ok_362 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 796068 with h363 | h363
  · exact okRange_sound check 12 793881 796068 ok_363 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 798255 with h364 | h364
  · exact okRange_sound check 12 796068 798255 ok_364 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 800442 with h365 | h365
  · exact okRange_sound check 12 798255 800442 ok_365 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 802629 with h366 | h366
  · exact okRange_sound check 12 800442 802629 ok_366 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 804816 with h367 | h367
  · exact okRange_sound check 12 802629 804816 ok_367 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 807003 with h368 | h368
  · exact okRange_sound check 12 804816 807003 ok_368 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 809190 with h369 | h369
  · exact okRange_sound check 12 807003 809190 ok_369 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 811377 with h370 | h370
  · exact okRange_sound check 12 809190 811377 ok_370 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 813564 with h371 | h371
  · exact okRange_sound check 12 811377 813564 ok_371 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 815751 with h372 | h372
  · exact okRange_sound check 12 813564 815751 ok_372 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 817938 with h373 | h373
  · exact okRange_sound check 12 815751 817938 ok_373 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 820125 with h374 | h374
  · exact okRange_sound check 12 817938 820125 ok_374 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 822312 with h375 | h375
  · exact okRange_sound check 12 820125 822312 ok_375 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 824499 with h376 | h376
  · exact okRange_sound check 12 822312 824499 ok_376 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 826686 with h377 | h377
  · exact okRange_sound check 12 824499 826686 ok_377 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 828873 with h378 | h378
  · exact okRange_sound check 12 826686 828873 ok_378 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 831060 with h379 | h379
  · exact okRange_sound check 12 828873 831060 ok_379 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 833247 with h380 | h380
  · exact okRange_sound check 12 831060 833247 ok_380 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 835434 with h381 | h381
  · exact okRange_sound check 12 833247 835434 ok_381 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 837621 with h382 | h382
  · exact okRange_sound check 12 835434 837621 ok_382 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 839808 with h383 | h383
  · exact okRange_sound check 12 837621 839808 ok_383 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 841995 with h384 | h384
  · exact okRange_sound check 12 839808 841995 ok_384 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 844182 with h385 | h385
  · exact okRange_sound check 12 841995 844182 ok_385 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 846369 with h386 | h386
  · exact okRange_sound check 12 844182 846369 ok_386 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 848556 with h387 | h387
  · exact okRange_sound check 12 846369 848556 ok_387 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 850743 with h388 | h388
  · exact okRange_sound check 12 848556 850743 ok_388 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 852930 with h389 | h389
  · exact okRange_sound check 12 850743 852930 ok_389 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 855117 with h390 | h390
  · exact okRange_sound check 12 852930 855117 ok_390 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 857304 with h391 | h391
  · exact okRange_sound check 12 855117 857304 ok_391 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 859491 with h392 | h392
  · exact okRange_sound check 12 857304 859491 ok_392 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 861678 with h393 | h393
  · exact okRange_sound check 12 859491 861678 ok_393 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 863865 with h394 | h394
  · exact okRange_sound check 12 861678 863865 ok_394 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 866052 with h395 | h395
  · exact okRange_sound check 12 863865 866052 ok_395 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 868239 with h396 | h396
  · exact okRange_sound check 12 866052 868239 ok_396 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 870426 with h397 | h397
  · exact okRange_sound check 12 868239 870426 ok_397 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 872613 with h398 | h398
  · exact okRange_sound check 12 870426 872613 ok_398 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 874800 with h399 | h399
  · exact okRange_sound check 12 872613 874800 ok_399 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 876987 with h400 | h400
  · exact okRange_sound check 12 874800 876987 ok_400 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 879174 with h401 | h401
  · exact okRange_sound check 12 876987 879174 ok_401 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 881361 with h402 | h402
  · exact okRange_sound check 12 879174 881361 ok_402 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 883548 with h403 | h403
  · exact okRange_sound check 12 881361 883548 ok_403 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 885735 with h404 | h404
  · exact okRange_sound check 12 883548 885735 ok_404 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 887922 with h405 | h405
  · exact okRange_sound check 12 885735 887922 ok_405 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 890109 with h406 | h406
  · exact okRange_sound check 12 887922 890109 ok_406 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 892296 with h407 | h407
  · exact okRange_sound check 12 890109 892296 ok_407 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 894483 with h408 | h408
  · exact okRange_sound check 12 892296 894483 ok_408 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 896670 with h409 | h409
  · exact okRange_sound check 12 894483 896670 ok_409 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 898857 with h410 | h410
  · exact okRange_sound check 12 896670 898857 ok_410 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 901044 with h411 | h411
  · exact okRange_sound check 12 898857 901044 ok_411 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 903231 with h412 | h412
  · exact okRange_sound check 12 901044 903231 ok_412 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 905418 with h413 | h413
  · exact okRange_sound check 12 903231 905418 ok_413 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 907605 with h414 | h414
  · exact okRange_sound check 12 905418 907605 ok_414 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 909792 with h415 | h415
  · exact okRange_sound check 12 907605 909792 ok_415 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 911979 with h416 | h416
  · exact okRange_sound check 12 909792 911979 ok_416 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 914166 with h417 | h417
  · exact okRange_sound check 12 911979 914166 ok_417 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 916353 with h418 | h418
  · exact okRange_sound check 12 914166 916353 ok_418 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 918540 with h419 | h419
  · exact okRange_sound check 12 916353 918540 ok_419 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 920727 with h420 | h420
  · exact okRange_sound check 12 918540 920727 ok_420 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 922914 with h421 | h421
  · exact okRange_sound check 12 920727 922914 ok_421 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 925101 with h422 | h422
  · exact okRange_sound check 12 922914 925101 ok_422 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 927288 with h423 | h423
  · exact okRange_sound check 12 925101 927288 ok_423 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 929475 with h424 | h424
  · exact okRange_sound check 12 927288 929475 ok_424 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 931662 with h425 | h425
  · exact okRange_sound check 12 929475 931662 ok_425 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 933849 with h426 | h426
  · exact okRange_sound check 12 931662 933849 ok_426 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 936036 with h427 | h427
  · exact okRange_sound check 12 933849 936036 ok_427 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 938223 with h428 | h428
  · exact okRange_sound check 12 936036 938223 ok_428 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 940410 with h429 | h429
  · exact okRange_sound check 12 938223 940410 ok_429 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 942597 with h430 | h430
  · exact okRange_sound check 12 940410 942597 ok_430 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 944784 with h431 | h431
  · exact okRange_sound check 12 942597 944784 ok_431 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 946971 with h432 | h432
  · exact okRange_sound check 12 944784 946971 ok_432 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 949158 with h433 | h433
  · exact okRange_sound check 12 946971 949158 ok_433 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 951345 with h434 | h434
  · exact okRange_sound check 12 949158 951345 ok_434 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 953532 with h435 | h435
  · exact okRange_sound check 12 951345 953532 ok_435 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 955719 with h436 | h436
  · exact okRange_sound check 12 953532 955719 ok_436 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 957906 with h437 | h437
  · exact okRange_sound check 12 955719 957906 ok_437 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 960093 with h438 | h438
  · exact okRange_sound check 12 957906 960093 ok_438 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 962280 with h439 | h439
  · exact okRange_sound check 12 960093 962280 ok_439 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 964467 with h440 | h440
  · exact okRange_sound check 12 962280 964467 ok_440 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 966654 with h441 | h441
  · exact okRange_sound check 12 964467 966654 ok_441 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 968841 with h442 | h442
  · exact okRange_sound check 12 966654 968841 ok_442 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 971028 with h443 | h443
  · exact okRange_sound check 12 968841 971028 ok_443 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 973215 with h444 | h444
  · exact okRange_sound check 12 971028 973215 ok_444 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 975402 with h445 | h445
  · exact okRange_sound check 12 973215 975402 ok_445 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 977589 with h446 | h446
  · exact okRange_sound check 12 975402 977589 ok_446 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 979776 with h447 | h447
  · exact okRange_sound check 12 977589 979776 ok_447 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 981963 with h448 | h448
  · exact okRange_sound check 12 979776 981963 ok_448 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 984150 with h449 | h449
  · exact okRange_sound check 12 981963 984150 ok_449 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 986337 with h450 | h450
  · exact okRange_sound check 12 984150 986337 ok_450 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 988524 with h451 | h451
  · exact okRange_sound check 12 986337 988524 ok_451 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 990711 with h452 | h452
  · exact okRange_sound check 12 988524 990711 ok_452 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 992898 with h453 | h453
  · exact okRange_sound check 12 990711 992898 ok_453 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 995085 with h454 | h454
  · exact okRange_sound check 12 992898 995085 ok_454 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 997272 with h455 | h455
  · exact okRange_sound check 12 995085 997272 ok_455 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 999459 with h456 | h456
  · exact okRange_sound check 12 997272 999459 ok_456 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1001646 with h457 | h457
  · exact okRange_sound check 12 999459 1001646 ok_457 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1003833 with h458 | h458
  · exact okRange_sound check 12 1001646 1003833 ok_458 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1006020 with h459 | h459
  · exact okRange_sound check 12 1003833 1006020 ok_459 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1008207 with h460 | h460
  · exact okRange_sound check 12 1006020 1008207 ok_460 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1010394 with h461 | h461
  · exact okRange_sound check 12 1008207 1010394 ok_461 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1012581 with h462 | h462
  · exact okRange_sound check 12 1010394 1012581 ok_462 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1014768 with h463 | h463
  · exact okRange_sound check 12 1012581 1014768 ok_463 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1016955 with h464 | h464
  · exact okRange_sound check 12 1014768 1016955 ok_464 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1019142 with h465 | h465
  · exact okRange_sound check 12 1016955 1019142 ok_465 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1021329 with h466 | h466
  · exact okRange_sound check 12 1019142 1021329 ok_466 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1023516 with h467 | h467
  · exact okRange_sound check 12 1021329 1023516 ok_467 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1025703 with h468 | h468
  · exact okRange_sound check 12 1023516 1025703 ok_468 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1027890 with h469 | h469
  · exact okRange_sound check 12 1025703 1027890 ok_469 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1030077 with h470 | h470
  · exact okRange_sound check 12 1027890 1030077 ok_470 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1032264 with h471 | h471
  · exact okRange_sound check 12 1030077 1032264 ok_471 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1034451 with h472 | h472
  · exact okRange_sound check 12 1032264 1034451 ok_472 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1036638 with h473 | h473
  · exact okRange_sound check 12 1034451 1036638 ok_473 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1038825 with h474 | h474
  · exact okRange_sound check 12 1036638 1038825 ok_474 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1041012 with h475 | h475
  · exact okRange_sound check 12 1038825 1041012 ok_475 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1043199 with h476 | h476
  · exact okRange_sound check 12 1041012 1043199 ok_476 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1045386 with h477 | h477
  · exact okRange_sound check 12 1043199 1045386 ok_477 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1047573 with h478 | h478
  · exact okRange_sound check 12 1045386 1047573 ok_478 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1049760 with h479 | h479
  · exact okRange_sound check 12 1047573 1049760 ok_479 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1051947 with h480 | h480
  · exact okRange_sound check 12 1049760 1051947 ok_480 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1054134 with h481 | h481
  · exact okRange_sound check 12 1051947 1054134 ok_481 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1056321 with h482 | h482
  · exact okRange_sound check 12 1054134 1056321 ok_482 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1058508 with h483 | h483
  · exact okRange_sound check 12 1056321 1058508 ok_483 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1060695 with h484 | h484
  · exact okRange_sound check 12 1058508 1060695 ok_484 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1062882 with h485 | h485
  · exact okRange_sound check 12 1060695 1062882 ok_485 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1065069 with h486 | h486
  · exact okRange_sound check 12 1062882 1065069 ok_486 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1067256 with h487 | h487
  · exact okRange_sound check 12 1065069 1067256 ok_487 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1069443 with h488 | h488
  · exact okRange_sound check 12 1067256 1069443 ok_488 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1071630 with h489 | h489
  · exact okRange_sound check 12 1069443 1071630 ok_489 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1073817 with h490 | h490
  · exact okRange_sound check 12 1071630 1073817 ok_490 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1076004 with h491 | h491
  · exact okRange_sound check 12 1073817 1076004 ok_491 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1078191 with h492 | h492
  · exact okRange_sound check 12 1076004 1078191 ok_492 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1080378 with h493 | h493
  · exact okRange_sound check 12 1078191 1080378 ok_493 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1082565 with h494 | h494
  · exact okRange_sound check 12 1080378 1082565 ok_494 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1084752 with h495 | h495
  · exact okRange_sound check 12 1082565 1084752 ok_495 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1086939 with h496 | h496
  · exact okRange_sound check 12 1084752 1086939 ok_496 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1089126 with h497 | h497
  · exact okRange_sound check 12 1086939 1089126 ok_497 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1091313 with h498 | h498
  · exact okRange_sound check 12 1089126 1091313 ok_498 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1093500 with h499 | h499
  · exact okRange_sound check 12 1091313 1093500 ok_499 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1095687 with h500 | h500
  · exact okRange_sound check 12 1093500 1095687 ok_500 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1097874 with h501 | h501
  · exact okRange_sound check 12 1095687 1097874 ok_501 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1100061 with h502 | h502
  · exact okRange_sound check 12 1097874 1100061 ok_502 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1102248 with h503 | h503
  · exact okRange_sound check 12 1100061 1102248 ok_503 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1104435 with h504 | h504
  · exact okRange_sound check 12 1102248 1104435 ok_504 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1106622 with h505 | h505
  · exact okRange_sound check 12 1104435 1106622 ok_505 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1108809 with h506 | h506
  · exact okRange_sound check 12 1106622 1108809 ok_506 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1110996 with h507 | h507
  · exact okRange_sound check 12 1108809 1110996 ok_507 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1113183 with h508 | h508
  · exact okRange_sound check 12 1110996 1113183 ok_508 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1115370 with h509 | h509
  · exact okRange_sound check 12 1113183 1115370 ok_509 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1117557 with h510 | h510
  · exact okRange_sound check 12 1115370 1117557 ok_510 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1119744 with h511 | h511
  · exact okRange_sound check 12 1117557 1119744 ok_511 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1121931 with h512 | h512
  · exact okRange_sound check 12 1119744 1121931 ok_512 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1124118 with h513 | h513
  · exact okRange_sound check 12 1121931 1124118 ok_513 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1126305 with h514 | h514
  · exact okRange_sound check 12 1124118 1126305 ok_514 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1128492 with h515 | h515
  · exact okRange_sound check 12 1126305 1128492 ok_515 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1130679 with h516 | h516
  · exact okRange_sound check 12 1128492 1130679 ok_516 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1132866 with h517 | h517
  · exact okRange_sound check 12 1130679 1132866 ok_517 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1135053 with h518 | h518
  · exact okRange_sound check 12 1132866 1135053 ok_518 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1137240 with h519 | h519
  · exact okRange_sound check 12 1135053 1137240 ok_519 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1139427 with h520 | h520
  · exact okRange_sound check 12 1137240 1139427 ok_520 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1141614 with h521 | h521
  · exact okRange_sound check 12 1139427 1141614 ok_521 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1143801 with h522 | h522
  · exact okRange_sound check 12 1141614 1143801 ok_522 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1145988 with h523 | h523
  · exact okRange_sound check 12 1143801 1145988 ok_523 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1148175 with h524 | h524
  · exact okRange_sound check 12 1145988 1148175 ok_524 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1150362 with h525 | h525
  · exact okRange_sound check 12 1148175 1150362 ok_525 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1152549 with h526 | h526
  · exact okRange_sound check 12 1150362 1152549 ok_526 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1154736 with h527 | h527
  · exact okRange_sound check 12 1152549 1154736 ok_527 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1156923 with h528 | h528
  · exact okRange_sound check 12 1154736 1156923 ok_528 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1159110 with h529 | h529
  · exact okRange_sound check 12 1156923 1159110 ok_529 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1161297 with h530 | h530
  · exact okRange_sound check 12 1159110 1161297 ok_530 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1163484 with h531 | h531
  · exact okRange_sound check 12 1161297 1163484 ok_531 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1165671 with h532 | h532
  · exact okRange_sound check 12 1163484 1165671 ok_532 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1167858 with h533 | h533
  · exact okRange_sound check 12 1165671 1167858 ok_533 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1170045 with h534 | h534
  · exact okRange_sound check 12 1167858 1170045 ok_534 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1172232 with h535 | h535
  · exact okRange_sound check 12 1170045 1172232 ok_535 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1174419 with h536 | h536
  · exact okRange_sound check 12 1172232 1174419 ok_536 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1176606 with h537 | h537
  · exact okRange_sound check 12 1174419 1176606 ok_537 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1178793 with h538 | h538
  · exact okRange_sound check 12 1176606 1178793 ok_538 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1180980 with h539 | h539
  · exact okRange_sound check 12 1178793 1180980 ok_539 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1183167 with h540 | h540
  · exact okRange_sound check 12 1180980 1183167 ok_540 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1185354 with h541 | h541
  · exact okRange_sound check 12 1183167 1185354 ok_541 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1187541 with h542 | h542
  · exact okRange_sound check 12 1185354 1187541 ok_542 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1189728 with h543 | h543
  · exact okRange_sound check 12 1187541 1189728 ok_543 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1191915 with h544 | h544
  · exact okRange_sound check 12 1189728 1191915 ok_544 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1194102 with h545 | h545
  · exact okRange_sound check 12 1191915 1194102 ok_545 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1196289 with h546 | h546
  · exact okRange_sound check 12 1194102 1196289 ok_546 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1198476 with h547 | h547
  · exact okRange_sound check 12 1196289 1198476 ok_547 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1200663 with h548 | h548
  · exact okRange_sound check 12 1198476 1200663 ok_548 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1202850 with h549 | h549
  · exact okRange_sound check 12 1200663 1202850 ok_549 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1205037 with h550 | h550
  · exact okRange_sound check 12 1202850 1205037 ok_550 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1207224 with h551 | h551
  · exact okRange_sound check 12 1205037 1207224 ok_551 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1209411 with h552 | h552
  · exact okRange_sound check 12 1207224 1209411 ok_552 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1211598 with h553 | h553
  · exact okRange_sound check 12 1209411 1211598 ok_553 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1213785 with h554 | h554
  · exact okRange_sound check 12 1211598 1213785 ok_554 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1215972 with h555 | h555
  · exact okRange_sound check 12 1213785 1215972 ok_555 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1218159 with h556 | h556
  · exact okRange_sound check 12 1215972 1218159 ok_556 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1220346 with h557 | h557
  · exact okRange_sound check 12 1218159 1220346 ok_557 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1222533 with h558 | h558
  · exact okRange_sound check 12 1220346 1222533 ok_558 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1224720 with h559 | h559
  · exact okRange_sound check 12 1222533 1224720 ok_559 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1226907 with h560 | h560
  · exact okRange_sound check 12 1224720 1226907 ok_560 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1229094 with h561 | h561
  · exact okRange_sound check 12 1226907 1229094 ok_561 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1231281 with h562 | h562
  · exact okRange_sound check 12 1229094 1231281 ok_562 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1233468 with h563 | h563
  · exact okRange_sound check 12 1231281 1233468 ok_563 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1235655 with h564 | h564
  · exact okRange_sound check 12 1233468 1235655 ok_564 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1237842 with h565 | h565
  · exact okRange_sound check 12 1235655 1237842 ok_565 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1240029 with h566 | h566
  · exact okRange_sound check 12 1237842 1240029 ok_566 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1242216 with h567 | h567
  · exact okRange_sound check 12 1240029 1242216 ok_567 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1244403 with h568 | h568
  · exact okRange_sound check 12 1242216 1244403 ok_568 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1246590 with h569 | h569
  · exact okRange_sound check 12 1244403 1246590 ok_569 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1248777 with h570 | h570
  · exact okRange_sound check 12 1246590 1248777 ok_570 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1250964 with h571 | h571
  · exact okRange_sound check 12 1248777 1250964 ok_571 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1253151 with h572 | h572
  · exact okRange_sound check 12 1250964 1253151 ok_572 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1255338 with h573 | h573
  · exact okRange_sound check 12 1253151 1255338 ok_573 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1257525 with h574 | h574
  · exact okRange_sound check 12 1255338 1257525 ok_574 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1259712 with h575 | h575
  · exact okRange_sound check 12 1257525 1259712 ok_575 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1261899 with h576 | h576
  · exact okRange_sound check 12 1259712 1261899 ok_576 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1264086 with h577 | h577
  · exact okRange_sound check 12 1261899 1264086 ok_577 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1266273 with h578 | h578
  · exact okRange_sound check 12 1264086 1266273 ok_578 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1268460 with h579 | h579
  · exact okRange_sound check 12 1266273 1268460 ok_579 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1270647 with h580 | h580
  · exact okRange_sound check 12 1268460 1270647 ok_580 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1272834 with h581 | h581
  · exact okRange_sound check 12 1270647 1272834 ok_581 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1275021 with h582 | h582
  · exact okRange_sound check 12 1272834 1275021 ok_582 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1277208 with h583 | h583
  · exact okRange_sound check 12 1275021 1277208 ok_583 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1279395 with h584 | h584
  · exact okRange_sound check 12 1277208 1279395 ok_584 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1281582 with h585 | h585
  · exact okRange_sound check 12 1279395 1281582 ok_585 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1283769 with h586 | h586
  · exact okRange_sound check 12 1281582 1283769 ok_586 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1285956 with h587 | h587
  · exact okRange_sound check 12 1283769 1285956 ok_587 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1288143 with h588 | h588
  · exact okRange_sound check 12 1285956 1288143 ok_588 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1290330 with h589 | h589
  · exact okRange_sound check 12 1288143 1290330 ok_589 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1292517 with h590 | h590
  · exact okRange_sound check 12 1290330 1292517 ok_590 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1294704 with h591 | h591
  · exact okRange_sound check 12 1292517 1294704 ok_591 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1296891 with h592 | h592
  · exact okRange_sound check 12 1294704 1296891 ok_592 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1299078 with h593 | h593
  · exact okRange_sound check 12 1296891 1299078 ok_593 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1301265 with h594 | h594
  · exact okRange_sound check 12 1299078 1301265 ok_594 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1303452 with h595 | h595
  · exact okRange_sound check 12 1301265 1303452 ok_595 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1305639 with h596 | h596
  · exact okRange_sound check 12 1303452 1305639 ok_596 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1307826 with h597 | h597
  · exact okRange_sound check 12 1305639 1307826 ok_597 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1310013 with h598 | h598
  · exact okRange_sound check 12 1307826 1310013 ok_598 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1312200 with h599 | h599
  · exact okRange_sound check 12 1310013 1312200 ok_599 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1314387 with h600 | h600
  · exact okRange_sound check 12 1312200 1314387 ok_600 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1316574 with h601 | h601
  · exact okRange_sound check 12 1314387 1316574 ok_601 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1318761 with h602 | h602
  · exact okRange_sound check 12 1316574 1318761 ok_602 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1320948 with h603 | h603
  · exact okRange_sound check 12 1318761 1320948 ok_603 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1323135 with h604 | h604
  · exact okRange_sound check 12 1320948 1323135 ok_604 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1325322 with h605 | h605
  · exact okRange_sound check 12 1323135 1325322 ok_605 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1327509 with h606 | h606
  · exact okRange_sound check 12 1325322 1327509 ok_606 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1329696 with h607 | h607
  · exact okRange_sound check 12 1327509 1329696 ok_607 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1331883 with h608 | h608
  · exact okRange_sound check 12 1329696 1331883 ok_608 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1334070 with h609 | h609
  · exact okRange_sound check 12 1331883 1334070 ok_609 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1336257 with h610 | h610
  · exact okRange_sound check 12 1334070 1336257 ok_610 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1338444 with h611 | h611
  · exact okRange_sound check 12 1336257 1338444 ok_611 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1340631 with h612 | h612
  · exact okRange_sound check 12 1338444 1340631 ok_612 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1342818 with h613 | h613
  · exact okRange_sound check 12 1340631 1342818 ok_613 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1345005 with h614 | h614
  · exact okRange_sound check 12 1342818 1345005 ok_614 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1347192 with h615 | h615
  · exact okRange_sound check 12 1345005 1347192 ok_615 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1349379 with h616 | h616
  · exact okRange_sound check 12 1347192 1349379 ok_616 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1351566 with h617 | h617
  · exact okRange_sound check 12 1349379 1351566 ok_617 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1353753 with h618 | h618
  · exact okRange_sound check 12 1351566 1353753 ok_618 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1355940 with h619 | h619
  · exact okRange_sound check 12 1353753 1355940 ok_619 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1358127 with h620 | h620
  · exact okRange_sound check 12 1355940 1358127 ok_620 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1360314 with h621 | h621
  · exact okRange_sound check 12 1358127 1360314 ok_621 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1362501 with h622 | h622
  · exact okRange_sound check 12 1360314 1362501 ok_622 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1364688 with h623 | h623
  · exact okRange_sound check 12 1362501 1364688 ok_623 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1366875 with h624 | h624
  · exact okRange_sound check 12 1364688 1366875 ok_624 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1369062 with h625 | h625
  · exact okRange_sound check 12 1366875 1369062 ok_625 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1371249 with h626 | h626
  · exact okRange_sound check 12 1369062 1371249 ok_626 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1373436 with h627 | h627
  · exact okRange_sound check 12 1371249 1373436 ok_627 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1375623 with h628 | h628
  · exact okRange_sound check 12 1373436 1375623 ok_628 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1377810 with h629 | h629
  · exact okRange_sound check 12 1375623 1377810 ok_629 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1379997 with h630 | h630
  · exact okRange_sound check 12 1377810 1379997 ok_630 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1382184 with h631 | h631
  · exact okRange_sound check 12 1379997 1382184 ok_631 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1384371 with h632 | h632
  · exact okRange_sound check 12 1382184 1384371 ok_632 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1386558 with h633 | h633
  · exact okRange_sound check 12 1384371 1386558 ok_633 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1388745 with h634 | h634
  · exact okRange_sound check 12 1386558 1388745 ok_634 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1390932 with h635 | h635
  · exact okRange_sound check 12 1388745 1390932 ok_635 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1393119 with h636 | h636
  · exact okRange_sound check 12 1390932 1393119 ok_636 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1395306 with h637 | h637
  · exact okRange_sound check 12 1393119 1395306 ok_637 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1397493 with h638 | h638
  · exact okRange_sound check 12 1395306 1397493 ok_638 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1399680 with h639 | h639
  · exact okRange_sound check 12 1397493 1399680 ok_639 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1401867 with h640 | h640
  · exact okRange_sound check 12 1399680 1401867 ok_640 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1404054 with h641 | h641
  · exact okRange_sound check 12 1401867 1404054 ok_641 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1406241 with h642 | h642
  · exact okRange_sound check 12 1404054 1406241 ok_642 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1408428 with h643 | h643
  · exact okRange_sound check 12 1406241 1408428 ok_643 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1410615 with h644 | h644
  · exact okRange_sound check 12 1408428 1410615 ok_644 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1412802 with h645 | h645
  · exact okRange_sound check 12 1410615 1412802 ok_645 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1414989 with h646 | h646
  · exact okRange_sound check 12 1412802 1414989 ok_646 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1417176 with h647 | h647
  · exact okRange_sound check 12 1414989 1417176 ok_647 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1419363 with h648 | h648
  · exact okRange_sound check 12 1417176 1419363 ok_648 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1421550 with h649 | h649
  · exact okRange_sound check 12 1419363 1421550 ok_649 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1423737 with h650 | h650
  · exact okRange_sound check 12 1421550 1423737 ok_650 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1425924 with h651 | h651
  · exact okRange_sound check 12 1423737 1425924 ok_651 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1428111 with h652 | h652
  · exact okRange_sound check 12 1425924 1428111 ok_652 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1430298 with h653 | h653
  · exact okRange_sound check 12 1428111 1430298 ok_653 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1432485 with h654 | h654
  · exact okRange_sound check 12 1430298 1432485 ok_654 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1434672 with h655 | h655
  · exact okRange_sound check 12 1432485 1434672 ok_655 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1436859 with h656 | h656
  · exact okRange_sound check 12 1434672 1436859 ok_656 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1439046 with h657 | h657
  · exact okRange_sound check 12 1436859 1439046 ok_657 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1441233 with h658 | h658
  · exact okRange_sound check 12 1439046 1441233 ok_658 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1443420 with h659 | h659
  · exact okRange_sound check 12 1441233 1443420 ok_659 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1445607 with h660 | h660
  · exact okRange_sound check 12 1443420 1445607 ok_660 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1447794 with h661 | h661
  · exact okRange_sound check 12 1445607 1447794 ok_661 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1449981 with h662 | h662
  · exact okRange_sound check 12 1447794 1449981 ok_662 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1452168 with h663 | h663
  · exact okRange_sound check 12 1449981 1452168 ok_663 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1454355 with h664 | h664
  · exact okRange_sound check 12 1452168 1454355 ok_664 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1456542 with h665 | h665
  · exact okRange_sound check 12 1454355 1456542 ok_665 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1458729 with h666 | h666
  · exact okRange_sound check 12 1456542 1458729 ok_666 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1460916 with h667 | h667
  · exact okRange_sound check 12 1458729 1460916 ok_667 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1463103 with h668 | h668
  · exact okRange_sound check 12 1460916 1463103 ok_668 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1465290 with h669 | h669
  · exact okRange_sound check 12 1463103 1465290 ok_669 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1467477 with h670 | h670
  · exact okRange_sound check 12 1465290 1467477 ok_670 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1469664 with h671 | h671
  · exact okRange_sound check 12 1467477 1469664 ok_671 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1471851 with h672 | h672
  · exact okRange_sound check 12 1469664 1471851 ok_672 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1474038 with h673 | h673
  · exact okRange_sound check 12 1471851 1474038 ok_673 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1476225 with h674 | h674
  · exact okRange_sound check 12 1474038 1476225 ok_674 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1478412 with h675 | h675
  · exact okRange_sound check 12 1476225 1478412 ok_675 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1480599 with h676 | h676
  · exact okRange_sound check 12 1478412 1480599 ok_676 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1482786 with h677 | h677
  · exact okRange_sound check 12 1480599 1482786 ok_677 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1484973 with h678 | h678
  · exact okRange_sound check 12 1482786 1484973 ok_678 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1487160 with h679 | h679
  · exact okRange_sound check 12 1484973 1487160 ok_679 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1489347 with h680 | h680
  · exact okRange_sound check 12 1487160 1489347 ok_680 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1491534 with h681 | h681
  · exact okRange_sound check 12 1489347 1491534 ok_681 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1493721 with h682 | h682
  · exact okRange_sound check 12 1491534 1493721 ok_682 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1495908 with h683 | h683
  · exact okRange_sound check 12 1493721 1495908 ok_683 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1498095 with h684 | h684
  · exact okRange_sound check 12 1495908 1498095 ok_684 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1500282 with h685 | h685
  · exact okRange_sound check 12 1498095 1500282 ok_685 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1502469 with h686 | h686
  · exact okRange_sound check 12 1500282 1502469 ok_686 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1504656 with h687 | h687
  · exact okRange_sound check 12 1502469 1504656 ok_687 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1506843 with h688 | h688
  · exact okRange_sound check 12 1504656 1506843 ok_688 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1509030 with h689 | h689
  · exact okRange_sound check 12 1506843 1509030 ok_689 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1511217 with h690 | h690
  · exact okRange_sound check 12 1509030 1511217 ok_690 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1513404 with h691 | h691
  · exact okRange_sound check 12 1511217 1513404 ok_691 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1515591 with h692 | h692
  · exact okRange_sound check 12 1513404 1515591 ok_692 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1517778 with h693 | h693
  · exact okRange_sound check 12 1515591 1517778 ok_693 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1519965 with h694 | h694
  · exact okRange_sound check 12 1517778 1519965 ok_694 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1522152 with h695 | h695
  · exact okRange_sound check 12 1519965 1522152 ok_695 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1524339 with h696 | h696
  · exact okRange_sound check 12 1522152 1524339 ok_696 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1526526 with h697 | h697
  · exact okRange_sound check 12 1524339 1526526 ok_697 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1528713 with h698 | h698
  · exact okRange_sound check 12 1526526 1528713 ok_698 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1530900 with h699 | h699
  · exact okRange_sound check 12 1528713 1530900 ok_699 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1533087 with h700 | h700
  · exact okRange_sound check 12 1530900 1533087 ok_700 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1535274 with h701 | h701
  · exact okRange_sound check 12 1533087 1535274 ok_701 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1537461 with h702 | h702
  · exact okRange_sound check 12 1535274 1537461 ok_702 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1539648 with h703 | h703
  · exact okRange_sound check 12 1537461 1539648 ok_703 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1541835 with h704 | h704
  · exact okRange_sound check 12 1539648 1541835 ok_704 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1544022 with h705 | h705
  · exact okRange_sound check 12 1541835 1544022 ok_705 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1546209 with h706 | h706
  · exact okRange_sound check 12 1544022 1546209 ok_706 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1548396 with h707 | h707
  · exact okRange_sound check 12 1546209 1548396 ok_707 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1550583 with h708 | h708
  · exact okRange_sound check 12 1548396 1550583 ok_708 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1552770 with h709 | h709
  · exact okRange_sound check 12 1550583 1552770 ok_709 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1554957 with h710 | h710
  · exact okRange_sound check 12 1552770 1554957 ok_710 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1557144 with h711 | h711
  · exact okRange_sound check 12 1554957 1557144 ok_711 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1559331 with h712 | h712
  · exact okRange_sound check 12 1557144 1559331 ok_712 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1561518 with h713 | h713
  · exact okRange_sound check 12 1559331 1561518 ok_713 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1563705 with h714 | h714
  · exact okRange_sound check 12 1561518 1563705 ok_714 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1565892 with h715 | h715
  · exact okRange_sound check 12 1563705 1565892 ok_715 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1568079 with h716 | h716
  · exact okRange_sound check 12 1565892 1568079 ok_716 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1570266 with h717 | h717
  · exact okRange_sound check 12 1568079 1570266 ok_717 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1572453 with h718 | h718
  · exact okRange_sound check 12 1570266 1572453 ok_718 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1574640 with h719 | h719
  · exact okRange_sound check 12 1572453 1574640 ok_719 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1576827 with h720 | h720
  · exact okRange_sound check 12 1574640 1576827 ok_720 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1579014 with h721 | h721
  · exact okRange_sound check 12 1576827 1579014 ok_721 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1581201 with h722 | h722
  · exact okRange_sound check 12 1579014 1581201 ok_722 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1583388 with h723 | h723
  · exact okRange_sound check 12 1581201 1583388 ok_723 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1585575 with h724 | h724
  · exact okRange_sound check 12 1583388 1585575 ok_724 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1587762 with h725 | h725
  · exact okRange_sound check 12 1585575 1587762 ok_725 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1589949 with h726 | h726
  · exact okRange_sound check 12 1587762 1589949 ok_726 i (by omega) (by omega)
  rcases Nat.lt_or_ge i 1592136 with h727 | h727
  · exact okRange_sound check 12 1589949 1592136 ok_727 i (by omega) (by omega)
  exact okRange_sound check 12 1592136 1594323 ok_728 i (by omega) (by omega)

theorem classOK_all (m : ℕ) (hm : m < 3 ^ 14) (hm3 : m % 3 = 2) : ClassOK m := by
  have e : m = 3 * ((m - 2) / 3) + 2 := by omega
  have hi : (m - 2) / 3 < 1594323 := by
    have : (3 : ℕ) ^ 14 = 4782969 := by norm_num
    omega
  rw [e]
  exact classOK_of_checkM _ (check_all _ hi)

theorem hbounds : ∀ m, m < 3 ^ 14 → m % 3 = 2 → 1 ≤ c m ∧ c m ≤ Cmax :=
  fun m hm hm3 => (classOK_all m hm hm3).1

theorem hcert : CertOK 14 pp qq c := by
  intro m hm hm3
  have h := classOK_all m hm hm3
  have e : (3 : ℕ) ^ 14 = 4782969 := by norm_num
  rw [e]
  exact h.2

set_option maxHeartbeats 0 in
theorem c_eight : c 8 = 270437 := by decide +kernel

/-- THE THEOREM at level 14: γ = 50·log₂(101210/100000) = 0.8676. -/
theorem density_bound (y : ℕ) :
    270437 * 101210 ^ (50 * y) * 100000 ^ 100 ≤
      reachesOneCount (80000 * 2 ^ y + 1) *
        (16777216 * 100000 ^ (50 * y) * 101210 ^ 100) := by
  classical
  have hgrow := growth_root 14 (by norm_num) pp qq Cmax (by norm_num [pp, qq])
    (by norm_num [qq]) c hbounds hcert (10 * (50 * y) + L 8) (50 * y) 8 rfl
    (by norm_num) (by norm_num) ⟨0, rfl⟩
  have h8 : (8 : ℕ) % 3 ^ 14 = 8 := by norm_num
  rw [h8, c_eight] at hgrow
  have hcap : cap (50 * y) * 8 = 80000 * 2 ^ y := by
    unfold cap
    have h1 : 50 * y / 50 = y := by omega
    have h2 : 50 * y % 50 = 0 := by omega
    rw [h1, h2, show rt 0 = 10000 by decide]
    ring
  have hsub : treeSet 8 (cap (50 * y) * 8)
      ⊆ @Finset.filter _ (fun n => ∃ t, terras_iter t n = 1)
        (Classical.decPred _) (Finset.range (80000 * 2 ^ y + 1)) := by
    intro n hn
    rw [mem_treeSet] at hn
    rw [Finset.mem_filter, Finset.mem_range]
    obtain ⟨j, hj, _⟩ := hn.2
    constructor
    · rw [hcap] at hn
      omega
    · exact ⟨j + 3, by
        rw [← terras_iter_add, hj, terras_iter_three_eight]⟩
  have hcnt : cnt 8 (cap (50 * y) * 8) ≤
      reachesOneCount (80000 * 2 ^ y + 1) := by
    unfold reachesOneCount cnt
    exact Finset.card_le_card hsub
  unfold pp qq Cmax at hgrow
  calc 270437 * 101210 ^ (50 * y) * 100000 ^ 100
      ≤ cnt 8 (cap (50 * y) * 8) * (16777216 * 100000 ^ (50 * y) * 101210 ^ 100) := hgrow
    _ ≤ reachesOneCount (80000 * 2 ^ y + 1) *
        (16777216 * 100000 ^ (50 * y) * 101210 ^ 100) :=
        Nat.mul_le_mul_right _ hcnt

end K14
end Collatz
