#!/usr/bin/env python3
"""
Emit the Lean instantiation of the grid Krasikov–Lagarias growth theorem
(lean/Collatz/KLGrid.lean, `G50.growth_root`) at level k from a certificate
JSON produced by kl_grid_certificate.py.

Files written (namespace Collatz.K{k}):
  lean/Collatz/KL{k}Data.lean      shards, c, ClassOK, checkM, okRange + soundness
  lean/Collatz/KL{k}Check{g}.lean  `decide +kernel` shard theorems, GROUP shards per file
  lean/Collatz/KL{k}.lean          assembly and the density theorem

Build sequentially (memory ~20 GB per check file):
  for f in KL{k}Data KL{k}Check0 ... KL{k}; do lake build Collatz.$f; done

Usage: kl_lean_instance.py analysis/certs/klgrid_k14_101210_100000.json [shards_per_file]
"""
import json, sys, math

def main():
    sys.set_int_max_str_digits(0)
    J = json.load(open(sys.argv[1]))
    G = int(sys.argv[2]) if len(sys.argv) > 2 else 81
    k, p, q, N, S, nsh, Cmax, c8 = (J[x] for x in ("k", "p", "q", "N", "S", "nsh", "Cmax", "c_root8"))
    assert J["entry_bits"] == 32 and N == 3 ** (k - 1)
    P, H = 3 ** k, 3 ** (k - 1)
    gamma = 50 * math.log2(p / q)
    K = f"K{k}"
    shards = J["shards"]
    data = f'''/-
  Collatz — Level k = {k} certificate data ({nsh} shards of {S} 32-bit entries).
  Generated by analysis/kl_lean_instance.py; see KL{k}.lean. NO axioms.
-/
import Collatz.KLGrid

set_option exponentiation.threshold 2000
set_option maxRecDepth 100000

namespace Collatz
namespace {K}

open G50

{chr(10).join(f"def sh{j} : ℕ := {shards[j]}" for j in range(nsh))}

def shard : ℕ → ℕ
{chr(10).join(f"  | {j} => sh{j}" for j in range(nsh))}
  | _ => 0

def get (i : ℕ) : ℕ := (shard (i / {S}) >>> (32 * (i % {S}))) &&& 4294967295
def c (m : ℕ) : ℕ := get ((m - 2) / 3)
def pp : ℕ := {p}
def qq : ℕ := {q}
def Cmax : ℕ := {Cmax}

def ClassOK (m : ℕ) : Prop :=
  (1 ≤ c m ∧ c m ≤ Cmax) ∧
  (m % 9 = 5 → c m * pp ^ 100 ≤ c (4 * m % {P}) * qq ^ 100) ∧
  (m % 9 = 2 → c m * pp ^ 100 ≤ c (4 * m % {P}) * qq ^ 100 +
    cbarG {k} c ((4 * m - 2) % {P} / 3) * (pp ^ 79 * qq ^ 21)) ∧
  (m % 9 = 8 → c m * pp ^ 100 * qq ^ 29 ≤ c (4 * m % {P}) * qq ^ 129 +
    cbarG {k} c ((2 * m - 1) % {P} / 3) * pp ^ 129)

def checkM (m : ℕ) : Bool :=
  (decide (1 ≤ c m) && decide (c m ≤ Cmax)) &&
  (if m % 9 = 5 then decide (c m * pp ^ 100 ≤ c (4 * m % {P}) * qq ^ 100) else true) &&
  (if m % 9 = 2 then decide (c m * pp ^ 100 ≤ c (4 * m % {P}) * qq ^ 100 +
    cbarG {k} c ((4 * m - 2) % {P} / 3) * (pp ^ 79 * qq ^ 21)) else true) &&
  (if m % 9 = 8 then decide (c m * pp ^ 100 * qq ^ 29 ≤ c (4 * m % {P}) * qq ^ 129 +
    cbarG {k} c ((2 * m - 1) % {P} / 3) * pp ^ 129) else true)

theorem classOK_of_checkM (m : ℕ) (h : checkM m = true) : ClassOK m := by
  unfold checkM at h
  simp only [Bool.and_eq_true, decide_eq_true_eq] at h
  obtain ⟨⟨⟨h1, h2⟩, h5⟩, h8⟩ := h
  refine ⟨h1, ?_, ?_, ?_⟩
  · intro hm; rw [if_pos hm] at h2; exact of_decide_eq_true h2
  · intro hm; rw [if_pos hm] at h5; exact of_decide_eq_true h5
  · intro hm; rw [if_pos hm] at h8; exact of_decide_eq_true h8

def check (i : ℕ) : Bool := checkM (3 * i + 2)

def okRange (f : ℕ → Bool) : ℕ → ℕ → ℕ → Bool
  | 0, lo, hi => if hi ≤ lo then true else if hi = lo + 1 then f lo else false
  | fuel + 1, lo, hi =>
      if hi ≤ lo then true else if hi = lo + 1 then f lo
      else okRange f fuel lo ((lo + hi) / 2) && okRange f fuel ((lo + hi) / 2) hi

theorem okRange_sound (f : ℕ → Bool) : ∀ fuel lo hi, okRange f fuel lo hi = true →
    ∀ i, lo ≤ i → i < hi → f i = true := by
  intro fuel
  induction fuel with
  | zero =>
    intro lo hi h i h1 h2
    simp only [okRange] at h
    split_ifs at h with hle heq
    · omega
    · have : i = lo := by omega
      subst this; exact h
  | succ fuel ih =>
    intro lo hi h i h1 h2
    simp only [okRange] at h
    split_ifs at h with hle heq
    · omega
    · have : i = lo := by omega
      subst this; exact h
    · rw [Bool.and_eq_true] at h
      rcases lt_or_ge i ((lo + hi) / 2) with hi' | hi'
      · exact ih lo ((lo + hi) / 2) h.1 i h1 hi'
      · exact ih ((lo + hi) / 2) hi h.2 i hi' h2

end {K}
end Collatz
'''
    open(f"lean/Collatz/KL{k}Data.lean", "w").write(data)
    groups = [range(g, min(g + G, nsh)) for g in range(0, nsh, G)]
    for gi, rng in enumerate(groups):
        body = "\n".join(f"set_option maxHeartbeats 0 in\ntheorem ok_{j} : okRange check 12 {j*S} {(j+1)*S} = true := by decide +kernel\n" for j in rng)
        open(f"lean/Collatz/KL{k}Check{gi}.lean", "w").write(f'''/- Level {k} kernel check, shards {rng.start}..{rng.stop-1}. NO axioms. -/
import Collatz.KL{k}Data

set_option exponentiation.threshold 2000
set_option maxRecDepth 100000

namespace Collatz
namespace {K}
open G50

{body}
end {K}
end Collatz
''')
    proof = []
    for j in range(nsh):
        if j < nsh - 1:
            proof.append(f"  rcases Nat.lt_or_ge i {(j+1)*S} with h{j} | h{j}")
            proof.append(f"  · exact okRange_sound check 12 {j*S} {(j+1)*S} ok_{j} i (by omega) (by omega)")
        else:
            proof.append(f"  exact okRange_sound check 12 {j*S} {(j+1)*S} ok_{j} i (by omega) (by omega)")
    imports = "\n".join(f"import Collatz.KL{k}Check{gi}" for gi in range(len(groups)))
    final = f'''/-
  Collatz — A machine-verified density exponent at level k = {k}:
  γ = 50·log₂({p}/{q}) = {gamma:.4f}, beating the 2003 record 0.84.
  Generated by analysis/kl_lean_instance.py. {N} classes in {nsh} shards.
  This file contains NO axioms and NO claim to prove the conjecture.
-/
{imports}

set_option exponentiation.threshold 2000
set_option maxRecDepth 100000

namespace Collatz
namespace {K}
open G50

theorem check_all (i : ℕ) (hi : i < {H}) : check i = true := by
{chr(10).join(proof)}

theorem classOK_all (m : ℕ) (hm : m < 3 ^ {k}) (hm3 : m % 3 = 2) : ClassOK m := by
  have e : m = 3 * ((m - 2) / 3) + 2 := by omega
  have hi : (m - 2) / 3 < {H} := by
    have : (3 : ℕ) ^ {k} = {P} := by norm_num
    omega
  rw [e]
  exact classOK_of_checkM _ (check_all _ hi)

theorem hbounds : ∀ m, m < 3 ^ {k} → m % 3 = 2 → 1 ≤ c m ∧ c m ≤ Cmax :=
  fun m hm hm3 => (classOK_all m hm hm3).1

theorem hcert : CertOK {k} pp qq c := by
  intro m hm hm3
  have h := classOK_all m hm hm3
  have e : (3 : ℕ) ^ {k} = {P} := by norm_num
  rw [e]
  exact h.2

set_option maxHeartbeats 0 in
theorem c_eight : c 8 = {c8} := by decide +kernel

/-- THE THEOREM at level {k}: γ = 50·log₂({p}/{q}) = {gamma:.4f}. -/
theorem density_bound (y : ℕ) :
    {c8} * {p} ^ (50 * y) * {q} ^ 100 ≤
      reachesOneCount (80000 * 2 ^ y + 1) *
        ({Cmax} * {q} ^ (50 * y) * {p} ^ 100) := by
  classical
  have hgrow := growth_root {k} (by norm_num) pp qq Cmax (by norm_num [pp, qq])
    (by norm_num [qq]) c hbounds hcert (10 * (50 * y) + L 8) (50 * y) 8 rfl
    (by norm_num) (by norm_num) ⟨0, rfl⟩
  have h8 : (8 : ℕ) % 3 ^ {k} = 8 := by norm_num
  rw [h8, c_eight] at hgrow
  have hcap : cap (50 * y) * 8 = 80000 * 2 ^ y := by
    unfold cap
    have h1 : 50 * y / 50 = y := by omega
    have h2 : 50 * y % 50 = 0 := by omega
    rw [h1, h2, show rt 0 = 10000 by decide]
    ring
  have hsub : treeSet 8 (cap (50 * y) * 8)
      ⊆ @Finset.filter _ (fun n => ∃ t, terras_iter t n = 1)
        (Classical.decPred _) (Finset.range (80000 * 2 ^ y + 1)) := by
    intro n hn
    rw [mem_treeSet] at hn
    rw [Finset.mem_filter, Finset.mem_range]
    obtain ⟨j, hj, _⟩ := hn.2
    constructor
    · rw [hcap] at hn
      omega
    · exact ⟨j + 3, by
        rw [← terras_iter_add, hj, terras_iter_three_eight]⟩
  have hcnt : cnt 8 (cap (50 * y) * 8) ≤
      reachesOneCount (80000 * 2 ^ y + 1) := by
    unfold reachesOneCount cnt
    exact Finset.card_le_card hsub
  unfold pp qq Cmax at hgrow
  calc {c8} * {p} ^ (50 * y) * {q} ^ 100
      ≤ cnt 8 (cap (50 * y) * 8) * ({Cmax} * {q} ^ (50 * y) * {p} ^ 100) := hgrow
    _ ≤ reachesOneCount (80000 * 2 ^ y + 1) *
        ({Cmax} * {q} ^ (50 * y) * {p} ^ 100) :=
        Nat.mul_le_mul_right _ hcnt

end {K}
end Collatz
'''
    open(f"lean/Collatz/KL{k}.lean", "w").write(final)
    print(f"k={k}: wrote KL{k}Data, {len(groups)} check files, KL{k}; gamma={gamma:.4f}, c8={c8}")

if __name__ == "__main__":
    main()
