#!/usr/bin/env python3
"""Lift dominating merges to progressions and remove covered progressions.

The rules are exact conditional noncontraction descent certificates.
Their union is not claimed to cover all positive integers or all NC seeds.
"""
import argparse
import json
from pathlib import Path

from variable_length_surgery import scan
from word_surgery import orbit


def progression(cert):
    n, x = cert['seed'], cert['predecessor']
    t, s = cert['forward_time'], cert['inverse_time']
    j, k = cert['forward_odds'], cert['inverse_odds']
    a, b = 3**max(k-j, 0), 3**max(j-k, 0)
    A, B = 2**t*a, 2**s*b
    assert 0 < x < n and 0 < B <= A
    assert 3**j*a == 3**k*b
    # Shift back only while positivity and strict seed ordering survive.
    back = min((n-1)//A, (x-1)//B)
    if A > B:
        back = min(back, (n-x-1)//(A-B))
    n0, x0 = n-A*back, x-B*back
    assert 0 < x0 < n0
    assert orbit(n0, t)[1] == j and orbit(x0, s)[1] == k
    assert orbit(n0, t)[0] == orbit(x0, s)[0]
    assert all(2**i <= 3**orbit(x0, i)[1] for i in range(s+1))
    for Q in (0, 1, 7):
        N, X = n0+A*Q, x0+B*Q
        assert 0 < X < N
        assert orbit(N, t)[0] == orbit(X, s)[0]
    return dict(seed=n0, predecessor=x0, seed_step=A, predecessor_step=B,
                forward_time=t, inverse_time=s, forward_odds=j, inverse_odds=k)


def covers(rule, n):
    return n >= rule['seed'] and (n-rule['seed']) % rule['seed_step'] == 0


def compress(rules):
    # Smaller moduli are visited first; containment includes the lower bound.
    kept = []
    for rule in sorted(rules, key=lambda r: (r['seed_step'], r['seed'],
                                           r['forward_time']+r['inverse_time'])):
        if not any(rule['seed_step'] % old['seed_step'] == 0
                   and covers(old, rule['seed']) for old in kept):
            kept.append(rule)
    return kept


def build(depth=18):
    data = scan(depth, include_certificates=True)
    certs = data.pop('certificates')
    uncertified = data.pop('uncertified_seeds')
    raw = [progression(c) for c in certs]
    kept = compress(raw)
    assert all(any(covers(r, c['seed']) for r in kept) for c in certs)
    # No unresolved seed may acquire an in-budget rule through normalization.
    assert all(not any(covers(r, n) for r in kept) for n in uncertified)
    return dict(depth=depth, source_certificates=len(certs),
                distinct_progressions=len({(r['seed'], r['seed_step']) for r in raw}),
                retained_progressions=len(kept), kernel_validation_module='Collatz.MergeRuleTable',
                scope='conditional infinite progressions; no universal coverage',
                rules=kept)


def lean_source(data):
    entries = []
    for r in data['rules']:
        t, s = r['forward_time'], r['inverse_time']
        A, B = r['seed_step'], r['predecessor_step']
        assert A % 2**t == 0 and B % 2**s == 0
        entries.append(f"  ⟨{r['seed']}, {r['predecessor']}, {t}, {s}, "
                       f"{A//2**t}, {B//2**s}⟩")
    return '''import Collatz.MergeProgression

/-! Generated by analysis/merge_progressions.py --write-lean.
The kernel checks each rule; completeness of the search is not claimed. -/
namespace Collatz.MergeRuleTable

def rules : List MergeRule := [
''' + ',\n'.join(entries) + ''']

set_option maxRecDepth 100000 in
set_option maxHeartbeats 0 in
private theorem checked : rules.all (fun r => decide r.Valid) = true := by decide

/-- Every listed finite certificate meets all exact arithmetic obligations. -/
theorem rules_valid : ∀ r ∈ rules, r.Valid := by
  intro r hr
  exact of_decide_eq_true ((List.all_eq_true.mp checked) r hr)

/-- Every listed progression supplies a smaller noncontracting merging
seed, conditional on noncontraction of the original. No coverage claim. -/
theorem certified_rule_sound {r : MergeRule} (hr : r ∈ rules) (Q : ℕ)
    (hn : NeverContracts (r.original Q)) :
    0 < r.replacement Q ∧ r.replacement Q < r.original Q ∧
      NeverContracts (r.replacement Q) :=
  MergeRule.sound (rules_valid r hr) Q hn

end Collatz.MergeRuleTable
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--depth', type=int, default=18)
    parser.add_argument('--write-lean', action='store_true',
                        help='write the generated kernel-checked rule table')
    args = parser.parse_args()
    if not 1 <= args.depth <= 20:
        parser.error('depth must be between 1 and 20')
    data = build(args.depth)
    if args.write_lean:
        target = Path(__file__).resolve().parents[1] / 'lean/Collatz/MergeRuleTable.lean'
        target.write_text(lean_source(data))
    print(json.dumps(data, indent=2))
